const addNum = 21225;
const street = 'Bassett Ave';
const city = 'Port Charlotte';
const zip = '33952';
export const COMPANY_ADDRESS = `${addNum} ${street}, ${city}, FL ${zip}`;
export const TRAVEL_DISTANCE_CHARGE = 3; // $3.00 per mile
export const TRAVEL_DISTANCE_THRESHOLD = 15; // 15 miles
export const TRAVEL_DURATION_CHARGE = 2; // $2.00 per minute
export const TRAVEL_DURATION_THRESHOLD = 25; // 25 minutes
