export const PHONE_NUMBER = ['+1', '407', '414', '0012'].join('');
export const EMAIL_ADDRESS = ['Joshua', '@', 'SHS-Florida', '.', 'com'].join('');
export const CALL_BUTTON_TEXT = 'Call Us';
export const TEXT_BUTTON_TEXT = 'Text Us';
export const REVIEW_BUTTON_TEXT = 'Leave a Review';
export const URL = 'https://www.shs-florida.com';
export const FACEBOOK_URL = 'https://www.facebook.com/share/1QKetFEue6/';
export const INSTAGRAM_URL = 'https://www.instagram.com/schmidtshomeservices?igsh=MWwzdWdsdG80YTlveg==';
export const GOOGLE_URL = 'https://g.co/kgs/rkuMBm5';
export const GOOGLE_REVIEW_URL = 'https://g.page/r/CZdBLOah2hTLEBI/review';
