import { makeStyles } from '@mui/styles';

const useStyles = makeStyles((theme) => ({
  '@keyframes gradientMovement': {
    '0%': {
      backgroundPosition: '0% 0%', // Start at the top of the background image
    },
    '100%': {
      backgroundPosition: '0% -100%', // Move the background image UP by 100% of its own height
    },
  },
  heroContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    height: '65vh',
    [theme.breakpoints.down('md')]: {
      height: '75vh',
    },
    [theme.breakpoints.down('sm')]: {
      height: '100vh',
    },
  },
  heroContent: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    textAlign: 'center',
    background: 'linear-gradient(to bottom, rgba(27, 78, 130, 0.8), rgba(255, 255, 255, 0.8))',
    alignContent: 'bottom',
    padding: theme.spacing(4),
  },
  headerContainer: {
    gap: 0,
    marginBottom: theme.spacing(2),
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing(2),
    [theme.breakpoints.down('xs')]: {
      fontSize: 32,
    },
  },
  headerText: {},
  subheader: {},
  actionButtons: {
    display: 'flex',
    gap: theme.spacing(2),
    margin: theme.spacing(4),
    [theme.breakpoints.down('sm')]: {
      flexDirection: 'column',
      gap: theme.spacing(1.5),
    },
  },
  scrollIndicatorContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-end',
    position: 'absolute',
    bottom: 0,
    paddingBottom: theme.spacing(2),
  },
  scrollIcon: {
    fontSize: 30,
    background: `linear-gradient(to bottom, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark})`,
    backgroundSize: '100% 1000%',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    color: 'transparent',
    transform: 'translateZ(0)',
    backfaceVisibility: 'hidden',
    display: 'inline-block',
    lineHeight: '1',
    verticalAlign: 'middle',
    animationTimingFunction: 'linear',
    animation: '$gradientMovement 20s linear infinite',
  },
  scrollText: {
    fontSize: 24,
    marginLeft: theme.spacing(3),
    marginRight: theme.spacing(3),
    background: `linear-gradient(to bottom, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark}, 
      ${theme.palette.primary.main}, 
      ${theme.palette.secondary.dark})`,
    backgroundSize: '100% 1000%',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    color: 'transparent',
    transform: 'translateZ(0)',
    backfaceVisibility: 'hidden',
    display: 'inline-block',
    lineHeight: '1',
    verticalAlign: 'middle',
    animationTimingFunction: 'linear',
    animation: '$gradientMovement 20s linear infinite',
  },
}));

export default useStyles;
